### ISSUE TITLE
Grade

### ISSUE THREAD

**Issue by edysegura** [leandrobcastilho/t141-final-homework#2]
[Requirements' List](https://edysegura.gitbooks.io/introducao-ao-desenvolvimento-web/content/introducao/projeto_final.html)

- [x] Version Control
- [x] Domain Name
- [x] Server
- [x] CRUD (**Missing update**)
- [x] API
- [x] Report

**Comment by leandrobcastilho** [comment]
the admin page you can change the password (this is an update)
I agree that in product page the update doesn't work very well, but if you check the code I implemented, I make a little mistake (as you can see on the last commit)
https://github.com/leandrobcastilho/t141-final-homework/commit/446c3abc14e523940c07845a71f52a25ba976bd3
