### ISSUE TITLE
Interesting solution!

### ISSUE THREAD

**Issue by edysegura** [leandrobcastilho/t141-final-homework#3]
https://github.com/leandrobcastilho/t141-final-homework/blob/410b9083e3cf02f97bf2369e274d03c3cb755386/js/Debug.js#L1-L7

**Comment by leandrobcastilho** [comment]
thank you! Have you a suggestion for doing this better?
I didn't have time enough for research, exist other solution for this

**Comment by edysegura** [comment]
In a bigger solution would be nice to have a 3PP for that such as:

- https://github.com/pimterry/loglevel
- https://www.loggly.com/docs/javascript/
